### ISSUE TITLE
Misleading package information

### ISSUE THREAD

**Issue by robjmills** [alvsystems/sagepay-php-sdk#1]
Hi,

I think its worth pointing out that it's pretty misleading to claim this is the "Official SagePay PHP SDK for server and direct integrations" if you've taken _their_ integration and just made it composer-compatible. I've not had a chance to play with this yet, and it's a very useful piece of work, but I think it clearly mis-communicates the library authorship. This is dangerous for users who choose to take this at face value, when you yourself admit within the README that the underlying library may actually be out of date.

**Comment by alvsystems** [comment]
Okay noted, in that case I'll change the wording!
