### ISSUE TITLE
"The Basket format is invalid" error with value over 1000

### ISSUE THREAD

**Issue by levofski** [alvsystems/sagepay-php-sdk#2]
When submitting a basket with a value of more than 1000 currency units, Sagepay throws the following error :-

"3021 : INVALID : The Basket format is invalid"

The issue has a solution (http://stackoverflow.com/questions/25968111/sagepay-xml-basket) however it has not been fixed in Sagepay's library yet.

I will submit a pull request for the given solution.

**Comment by alvsystems** [comment]
Thanks for the fix. I've merged into the main branch now.
