### ISSUE TITLE
PHP 7.1 Function mcrypt_encrypt() is deprecated

### ISSUE THREAD

**Issue by sebastiansulinski** [alvsystems/sagepay-php-sdk#4]
On PHP 7.1 servers the deprecation error is being thrown.

```bash
Error: Function mcrypt_encrypt() is deprecated
File: ...vendor/alvsystems/sagepay-php-sdk/lib/classes/util.php
Line: 137
Number: 8192
```

**Comment by alvinchevolleaux** [comment]
Wow just saw this issue! Not sure my notifications were working but I'll look into this and see what I can do here.

**Comment by sebastiansulinski** [comment]
Cool - cheers.

**Comment by alvinchevolleaux** [comment]
I've decided to deprecate this library due to copyright issues and there are better alternatives.
